name: 'Generates a PR comment from the content of a SAFIR file'
description: 'Read a safir json report file and comment stats on to PR'
inputs:
  token:
    description: 'The GitHub authentication token'
    required: true
  path:
    description: 'Filepath to safir.json'
    required: true
  title:
    description: 'Comment title in PR conversation'
    required: false
    default: 'Security Report'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'message-square'
  color: 'gray-dark'
