name: run-dependency-check

on: [pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: npm install
    - run: npm run package

    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: test/_stubs/trivy-sarif.json
        title: Dependency Check
